add_newline = false

format = "$hostname $directory$git_branch$git_status$cmd_duration$character"

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[❯](bold green)"

[directory]
truncation_length = 3
truncate_to_repo = true
style = "bold purple"
format = "[$path]($style)[$read_only]($read_only_style) "
read_only = "RO"
read_only_style = "red"
truncation_symbol = ".../"
home_symbol = "~"

[git_branch]
symbol = " "
style = "bold purple"
format = "on [$symbol$branch]($style) "

[git_status]
style = "bold red"
format = "[$all_status$ahead_behind]($style) "

[cmd_duration]
min_time = 500
style = "bold yellow"
format = "took [$duration]($style) "

[hostname]
ssh_only = false
style = "bold cyan"
format = "[$hostname]($style)"
